version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - start_dependencies

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
    command: mysql:3306

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password

  docs:
    image: httpd:2.4
    volumes:
      - ./docs/:/usr/local/apache2/htdocs/
    ports:
      - 8081:80

  swagger:
    image: swaggerapi/swagger-ui
    # environment:
    #  API_URL: http://localhost:8081/docs.yml
    ports:
      - 8080:8080
    depends_on:
      - docs
